### ISSUE TITLE
Add moderation commands?

### ISSUE THREAD

**Issue by MrMudkip** [Stardust-Discord/Octave#62]
**Is your feature request related to a problem? Please describe.**
No

**Describe the idea you'd like**
Moderation commands? Also maybe make it so if someone were to be banned from Dank Memer, they would also be banned from using Octave?

**Describe alternatives you've considered**
N/A

**Additional context**
I am still banned from dank memer

**Comment by Devoxin** [comment]
Octave's primary focus is to be a music bot, thus there are no plans to introduce moderation features.

Also, Octave and Dank Memer are two separate services unrelated to each other, so your suggestion of bans applying to one another is not applicable.
