### ISSUE TITLE
_play no longer can play playlist

### ISSUE THREAD

**Issue by SandyRizky** [Stardust-Discord/Octave#64]
So i used to using the _play command for playing my youtube playlist, but starting from 26 September 2020 it's not working anymore, it just display the playlist name, and do nothing.

1. Go to one of discord server that have Octave in it.
2. on chat message type _play <YOUTUBE PLAYLIST URL> e.g : _play https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10
3. Press Enter or Submit
4. Playlist name displayed but not played

Expected behavior
Playlist added to queue and can be played.

**Comment by Draco-Zero** [comment]
I support and observe this problem not only in Octave. Many bots have a problem with playlists.

**Comment by SandyRizky** [comment]
if that so, and there's nothing we can do to fix it, i will close this issue. Thanks.
