### ISSUE TITLE
Wrong playlist name after editing and discarding

### ISSUE THREAD

**Issue by booleancoercion** [Stardust-Discord/Octave#65]
**Describe the bug**
When you edit a playlist's name in the edit mode and then discard the changes, the bot tells you that in order the change the playlist again you must use a wrong command.

**To Reproduce**
1. Create a playlist with any name (e.g. foo) using `-playlists create foo`
2. Edit the playlist using `-playlists edit foo`
3. Rename the playlist to anything (e.g. bar), by sending `rename bar`
4. Exit editing mode by typing `exit`
5. The bot will send the following message: "Discarded changes. If you wish to make any further modifications, re-run -cpl edit bar.". Running said command will not work.

**Expected behavior**
The bot should send the message with the old name of the playlist instead

**Screenshots**
None.

**Additional context**
None.

**Comment by booleancoercion** [comment]
I mean, sure, it's your bot

**Comment by Devoxin** [comment]
Hm? This was fixed...

**Comment by Devoxin** [comment]
OH! Sorry, I misread this actually.

**Comment by booleancoercion** [comment]
Oh, usually when someone closes an issue they also provide a reason so I thought that you might not be interested in fixing it, my mistake
