### ISSUE TITLE
Report: not sending feedback message 

### ISSUE THREAD

**Issue by LiviaRLA** [Stardust-Discord/Octave#68]
**Describe the bug**
The bot isn't sending feedback message after using the commands.

**To Reproduce**
use any command
_play
_help
...

**Expected behavior**
A feedback message after sending commands.

**Screenshots**
![image](https://user-images.githubusercontent.com/15388893/98834431-f780d880-241d-11eb-9e79-32e833ece2fc.png)

**Additional context**

**Comment by Bendall6456** [comment]
We are aware of the issue and the devs have been notified of this issue.
