### ISSUE TITLE
Code guidelines?

### ISSUE THREAD

**Issue by darklight147** [Stardust-Discord/Octave#70]

**Comment by Devoxin** [comment]
Can you elaborate?

**Comment by darklight147** [comment]
i read your contribution guideline
```
Must be:

Tested
Working
Follow code guidelines
In no way harms the bot or its owners
Can not be perceived as toxic
Most importantly, follows Discord ToS and Community Guidelines
```


and i was asking aboutn this line here:

>Follow code guidelines

**Comment by Devoxin** [comment]
Ah, yeah. I guess that should read as "Code of Conduct", which can be found [here](../blob/development/CODE_OF_CONDUCT.md). Hope this clears up any confusion! :)
